//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionAnswerPortal.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public System.DateTime DatePublished { get; set; }
        public string UserId { get; set; }
        public string Image { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
